evmNetworkId: 100
priceMultiplier: 1
assistivePricing: true
timeLabels:
  - name: "Time: <1 Hour"
  - name: "Time: <1 Day"
  - name: "Time: <1 Week"
  - name: "Time: <2 Weeks"
  - name: "Time: <1 Month"
priorityLabels:
  - name: "Priority: 0 (Normal)"
  - name: "Priority: 1 (Medium)"
  - name: "Priority: 2 (High)"
  - name: "Priority: 3 (Urgent)"
  - name: "Priority: 4 (Emergency)"
defaultLabels:
  - "Time: <1 Hour"
  - "Priority: 1 (Normal)"
paymentPermitMaxPrice: 1000
commentIncentives: true
promotionComment: "<h6>If you've enjoyed your experience in the DevPool, we'd appreciate your support. Follow <a href='https://github.com/ubiquity'>Ubiquity on GitHub</a> and star <a href='https://github.com/ubiquity/devpool-directory'>this repo</a>. Your endorsement means the world to us and helps us grow!</h6><h6>We are excited to announce that the DevPool and UbiquiBot are now available to partners! Our ideal collaborators are globally distributed crypto-native organizations, who actively work on open source on GitHub, and excel in research & development. If you can introduce us to the repository maintainers in these types of companies, we have a special bonus in store for you!</h6>"
registerWalletWithVerification: false
commandSettings:
  - name: start
    enabled: true
  - name: stop
    enabled: true
  - name: wallet
    enabled: true
  - name: payout
    enabled: true
  - name: multiplier
    enabled: true
  - name: query
    enabled: true
  - name: allow
    enabled: true
  - name: autopay
    enabled: true
  - name: incentivize
    enabled: true
  - name: "comment-incentive"
    enabled: true
privateKeyEncrypted: "GoBhfETSpBWPPFj_s2em46A-RkGT6piXGr_y_k3_YD-y1mE3zo1L66T7hfCx7Tg19B-9_41udoK1XeHtSxXVqn4ADamxxpInImnJgvpYtrYmNwZODmV53Sgb2X0WeWidtBOOOfkrNU0Gl-wnWRN7nA"
incentives:
  comment:
    elements:
      code: 10
      img: 1
      li: 1
      a: 1
      blockquote: 1
    totals:
      word: 1
