evm-network-id: 100
price-multiplier: 1.5
time-labels:
  - name: "Time: <1 Hour"
  - name: "Time: <2 Hours"
  - name: "Time: <4 Hours"
  - name: "Time: <1 Day"
  - name: "Time: <1 Week"
priority-labels:
  - name: "Priority: 1 (Normal)"
  - name: "Priority: 2 (Medium)"
  - name: "Priority: 3 (High)"
  - name: "Priority: 4 (Urgent)"
  - name: "Priority: 5 (Emergency)"
default-labels:
  - "Time: <1 Hour"
  - "Priority: 1 (Normal)"
payment-permit-max-price: 1000
comment-incentives: true
max-concurrent-bounties: 2
promotion-comment: "<h6>If you've enjoyed your experience in the DevPool, we'd appreciate your support. Follow <a href='https://github.com/ubiquity'>Ubiquity on GitHub</a> and star <a href='https://github.com/ubiquity/devpool-directory'>this repo</a>. Your endorsement means the world to us and helps us grow!</h6><h6>We are excited to announce that the DevPool and UbiquiBot are now available to partners! Our ideal collaborators are globally distributed crypto-native organizations, who actively work on open source on GitHub, and excel in research & development. If you can introduce us to the repository maintainers in these types of companies, we have a special bonus in store for you!</h6>"
incentives:
  comment:
    elements:
      code: 5
      img: 5
      h1: 1
      li: 0.5
      a: 0.5
      blockquote: 0
    totals:
      word: 0.1
register-wallet-with-verification: false
assistive-pricing: true
