evm-network-id: 100
price-multiplier: 1.5
time-labels:
  - name: "Time: <1 Hour"
    weight: 0.125
    value: 3600
  - name: "Time: <2 Hours"
    weight: 0.25
    value: 7200
  - name: "Time: <4 Hours"
    weight: 0.5
    value: 14400
  - name: "Time: <1 Day"
    weight: 1
    value: 86400
  - name: "Time: <1 Week"
    weight: 2
    value: 604800
priority-labels:
  - name: "Priority: 0 (Normal)"
    weight: 1
  - name: "Priority: 1 (Medium)"
    weight: 2
  - name: "Priority: 2 (High)"
    weight: 3
  - name: "Priority: 3 (Urgent)"
    weight: 4
  - name: "Priority: 4 (Emergency)"
    weight: 5
default-labels:
  - "Time: <1 Hour"
  - "Priority: 0 (Normal)"
payment-permit-max-price: 1000
comment-incentives: true
max-concurrent-bounties: 2
promotion-comment: "\n<h6>If you enjoy the DevPool experience, please follow <a href='https://github.com/ubiquity'>Ubiquity on GitHub</a> and star <a href='https://github.com/ubiquity/devpool-directory'>this repo</a> to show your support. It helps a lot!</h6>"
incentives:
  comment:
    elements:
      code: 5
      img: 5
      h1: 1
      li: 0.5
      a: 0.5
      blockquote: 0
    totals:
      word: 0.1
register-wallet-with-verification: false
assistive-pricing: true
