name: Automate QA

on:
  pull_request:
    types:
      - review_requested
    branches: [development,main]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: add pr to project
        if: contains(github.event.pull_request.requested_reviewers.*.login, 'Draeieg')
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/ubiquity/projects/23
          github-token: ${{ secrets.ADD_TO_PROJECT }}

      - name: Create QA Issue
        if: contains(github.event.pull_request.requested_reviewers.*.login, 'Draeieg')
        uses: dacbd/create-issue-action@v1
        with:
          token: ${{ secrets.ADD_TO_PROJECT }}
          org: ubiquibot
          repo: staging
          title: QA for ${{ github.event.pull_request.title }}
          body: |
            Testing pr <a href="${{ github.event.pull_request.html_url }}">${{ github.event.pull_request.number }}</a>
