name: Automate QA

on:
  pull_request_target:
    types:
      - review_requested
    branches: [development, main]

jobs:
  add-to-project:
    env:
      ADD_TO_PROJECT_PAT: ${{ secrets.ADD_TO_PROJECT_PAT }}
    name: Add issue to project
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add PR to QA project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/ubiquity/projects/23
          github-token: ${{ env.ADD_TO_PROJECT_PAT }}

      - name: Create QA Issue
        uses: dacbd/create-issue-action@v1
        with:
          token: ${{ env.ADD_TO_PROJECT_PAT }}
          owner: ubiquibot
          repo: staging
          title: QA for ${{ github.event.pull_request.title }}
          body: |
            Testing pr <a href="${{ github.event.pull_request.html_url }}">${{ github.event.pull_request.number }}</a>
